### ISSUE TITLE
opcode 

### ISSUE THREAD

**Issue by mr-tron** [pyAndr3w/ton-preprocessed-wallet-v2#11]
if in the future code will be upgraded for supporting new features (and new feature means ability to process another types of incoming messages) you will broke support of current mesages.
something like 
`msg_body$_ {n:#} op_code:bits32 sign:bits512 ^(MsgInner n) = ExtInMsgBody n;`
where simple code setting c5 have some hardcoded op_code value and reject messages with over opcodes.

**Comment by cryshado** [comment]
No, it will increase gas consumption and destroys the current ideology
