### ISSUE TITLE
seqno should be bigger than 16 bits

### ISSUE THREAD

**Issue by mr-tron** [pyAndr3w/ton-preprocessed-wallet-v2#8]
a lot of accounts has more than 65535 transactions. it's dangerous for bots for example if someone sets until to `2**64` for simplicity.` 2**32` bits costs no so much storage fee but remove this problem at all

**Comment by pyAndr3w** [comment]
after 65535 seqno will be reset and a new loop will start

https://github.com/pyAndr3w/ton-preprocessed-wallet-v2/blob/aebadc7ba6ff8fc7f99c98b22ec2197fd7e94038/code.fif#L28

**Comment by mr-tron** [comment]
i understand. but why not 8 bits in this case? i know bot developers. they often use immortal transactions. even one suddenly added immortal transaction can be repeated on each loop.

**Comment by cryshado** [comment]
> i understand. but why not 8 bits in this case? i know bot developers. they often use immortal transactions. even one suddenly added immortal transaction can be repeated on each loop.

8 bit it's just 256 values, this may not be enough if expire_at is large
