### ISSUE TITLE
please add support for internals

### ISSUE THREAD

**Issue by mr-tron** [pyAndr3w/ton-preprocessed-wallet-v2#9]
it's useful for sending more than 254 messages with one external and for gasless jettons and nfts transfer.
it's not more dangerous because still require signature and over checks

**Comment by cryshado** [comment]
No.
![68f87b37ccfde22769262c7cdc7b2b0b_w200](https://github.com/pyAndr3w/ton-preprocessed-wallet-v2/assets/46900925/a5b1826f-7c3f-4f15-83b6-6b7b4d39e92b)
